import type { SiteLocale } from "../../lib/i18n";

const homePageContentMap = {
  ja: {
    pageTitle: undefined,
    latestArticlesEyebrow: "Latest Articles",
    latestArticlesHeading: "最新の記事",
    latestArticlesCta: "記事一覧を見る",
    latestReleasesEyebrow: "Latest Releases",
    latestReleasesHeading: "最新のリリース",
    latestReleasesCta: "アセット一覧を見る",
    gamesEyebrow: "Games",
    gamesHeading: "ゲーム",
    gamesCta: "ゲーム一覧を見る",
    heroPrimaryCta: "プロフィールを見る",
    heroContactCta: "問い合わせ",
    aboutEyebrow: "About",
    aboutHeading: "活動の正本をここに集約する",
    aboutBody: "外部サービスに依存しすぎず、プロフィール、作品、記事、連絡導線を一か所で追える構成に切り替えています。",
    aboutCta: "プロフィールを見る",
    homeHeading: "ホーム",
  },
  en: {
    pageTitle: undefined,
    latestArticlesEyebrow: "Latest Articles",
    latestArticlesHeading: "Latest Articles",
    latestArticlesCta: "View Articles",
    latestReleasesEyebrow: "Latest Releases",
    latestReleasesHeading: "Latest Releases",
    latestReleasesCta: "View Assets",
    gamesEyebrow: "Games",
    gamesHeading: "Games",
    gamesCta: "View Games",
    heroPrimaryCta: "View Profile",
    heroContactCta: "Contact",
    aboutEyebrow: "About",
    aboutHeading: "A single source of truth for ongoing work",
    aboutBody: "The site is being rebuilt so profile, projects, writing, and contact paths can be followed in one place without leaning too heavily on external services.",
    aboutCta: "About",
    homeHeading: "Home",
  },
  "zh-hant": {
    pageTitle: undefined,
    latestArticlesEyebrow: "Latest Articles",
    latestArticlesHeading: "最新文章",
    latestArticlesCta: "查看文章列表",
    latestReleasesEyebrow: "Latest Releases",
    latestReleasesHeading: "最新發佈",
    latestReleasesCta: "查看資產列表",
    gamesEyebrow: "Games",
    gamesHeading: "遊戲",
    gamesCta: "查看遊戲列表",
    heroPrimaryCta: "查看個人簡介",
    heroContactCta: "聯絡",
    aboutEyebrow: "About",
    aboutHeading: "把持續中的活動集中在同一個正本",
    aboutBody: "這個網站正在重整為一個可以在同一處追蹤個人簡介、作品、文章與聯絡方式的據點，避免過度依賴外部服務。",
    aboutCta: "查看個人簡介",
    homeHeading: "首頁",
  },
  ko: {
    pageTitle: undefined,
    latestArticlesEyebrow: "Latest Articles",
    latestArticlesHeading: "최신 글",
    latestArticlesCta: "글 목록 보기",
    latestReleasesEyebrow: "Latest Releases",
    latestReleasesHeading: "최신 릴리스",
    latestReleasesCta: "에셋 목록 보기",
    gamesEyebrow: "Games",
    gamesHeading: "게임",
    gamesCta: "게임 목록 보기",
    heroPrimaryCta: "소개 보기",
    heroContactCta: "문의",
    aboutEyebrow: "About",
    aboutHeading: "진행 중인 활동을 한곳의 원본으로 모으기",
    aboutBody: "이 사이트는 프로필, 작업물, 글, 연락 경로를 한곳에서 따라갈 수 있도록 외부 서비스 의존을 줄이며 다시 구성하고 있습니다.",
    aboutCta: "소개 보기",
    homeHeading: "홈",
  },
} as const;

export function getHomePageContent(locale: SiteLocale) {
  return homePageContentMap[locale];
}
